---

- name: 'Set variable pmm config flags'
  set_fact:
    pmm_extended_client_config_flags: >
      {%  set _pmm_extended_client_config_flags = [] -%}
      {%- if pmm_add_client_config['flags'] is defined -%}
      {%-   for _pmm_add_client_config_flag, _pmm_add_client_config_value in pmm_add_client_config['flags'].items() -%}
      {%-     if _pmm_add_client_config_value == '' -%}
      {{-       _pmm_extended_client_config_flags.append('--' + _pmm_add_client_config_flag) -}}
      {%-     else -%}
      {{-       _pmm_extended_client_config_flags.append('--' + _pmm_add_client_config_flag + '=' + _pmm_add_client_config_value) -}}
      {%-     endif -%}
      {%-   endfor -%}
      {%- endif -%}
      {{- _pmm_extended_client_config_flags | list }}

- name: 'Set variable pmm config args'
  set_fact:
    pmm_extended_client_config_args: "{{ pmm_add_client_config['args'] | join(' ') if pmm_add_client_config['args'] is defined else '' }}"

- name: 'Set variable pmm config extended'
  set_fact:
    pmm_extended_client_config: "{{ pmm_extended_client_config_flags | join(' ') + ' ' + pmm_extended_client_config_args }}"

- name: 'Set variable pmm config'
  set_fact:
    pmm_client_config: "{{ pmm_base_client_config + ' ' + pmm_extended_client_config }}"

- name: Check if PMM Client is configured
  command: pmm-admin list
  ignore_errors: true
  register: pmm_admin_list
  changed_when: false

- name: Configure PMM Client
  command: pmm-admin config {{ pmm_client_config }}
  when: >
        (not ansible_check_mode) and
        (pmm_admin_list.stderr.find("pmm-agent is running, but not set up") != -1)
